### PR TITLE
feat(ff-engine+backends): PR-7b/3 cancel-family scanners trait-routed (cairn #436)

### PR DESCRIPTION
**Pull request by avifenesh**
## Summary

PR-7b Cluster 3 of the `cairn #436` scanner-trait migration. Routes the three RFC-016 cancel-family scanners through `EngineBackend` instead of direct `FCALL`s on the raw `ferriskey::Client`.

**Stacked on** #443 (Cluster 1). Rebase onto `main` once #443 merges.

## Scanners migrated (3)

- `scanner/cancel_reconciler.rs` — per-member cancel + ack
- `scanner/edge_cancel_dispatcher.rs` — per-sibling cancel + per-group drain
- `scanner/edge_cancel_reconciler.rs` — Invariant-Q6 reconcile disposition

## Semantic-match verification (existing trait reuse)

Per the brief, verified the two existing trait methods match scanner-internal usage before adding new ones:

**`EngineBackend::cancel_execution`** — scanner call sites in `cancel_reconciler::cancel_member` and `edge_cancel_dispatcher::cancel_sibling` build byte-identical KEYS[21]+ARGV[5] to the trait's `CancelExecutionArgs`-driven FCALL:
- both hardcode `source = "operator_override"` (matches `CancelSource::OperatorOverride`)
- both pass empty `lease_id` / `lease_epoch` (matches `None` / `None`)
- both use the same 21-KEY lane/worker index layout
- both parse identical reply shape (`Array[Int(1)]` = cancelled, `Array[Int(0), "execution_not_active"]` = already terminal, `Array[Int(0), "execution_not_found"]` = not found)

Lua error codes map through `ff_script::engine_error_ext` to:
- `execution_not_active` → `EngineError::Contention(ContentionKind::ExecutionNotActive { .. })` → treated as already-terminal
- `execution_not_found` → `EngineError::NotFound` → treated as not-found
- everything else → transient; retry next cycle

**Result: reuse, no new `cancel_execution_from_scanner` variant needed.**

**`EngineBackend::ack_cancel_member`** — trait signature `(&FlowId, &ExecutionId)` exactly matches the scanner's 2-KEY + 2-ARGV FCALL shape. Direct reuse.

## New trait methods (2) — RFC-016 Stage C + D

```rust
async fn drain_sibling_cancel_group(
    &self, flow_partition: Partition, flow_id: &FlowId,
    downstream_eid: &ExecutionId,
) -> Result<(), EngineError>;

async fn reconcile_sibling_cancel_group(
    &self, flow_partition: Partition, flow_id: &FlowId,
    downstream_eid: &ExecutionId,
) -> Result<SiblingCancelReconcileAction, EngineError>;

pub enum SiblingCancelReconcileAction {
    SremmedStale, CompletedDrain, NoOp,
}
```

## Backend coverage

- **Valkey**: real FCALL wrappers for both new methods (same KEYS/ARGV as scanner internals).
- **Postgres**: `Unavailable` default. PG's Wave-6b `reconcilers::edge_cancel_{dispatcher,reconciler}::*_tick` already own the equivalent batched SQL path. The Valkey-shaped per-tuple call is **not** on a cairn-consumer surface — these sibling-cancel group ops are scanner-internal primitives, not operator/worker APIs cairn calls. Per owner constraint #1, `Unavailable` is correct here.
- **SQLite**: `Unavailable` default (mirrors PG; RFC-023 scope).

`cancel_execution` + `ack_cancel_member` are already implemented on both PG (`operator::cancel_execution_impl` + `operator::ack_cancel_member_impl`) and Valkey (pre-PR-7b). No new backend SQL needed.

## Fallback paths

Legacy direct-FCALL paths preserved for construction sites without a wired backend (test harnesses + `EdgeCancelDispatcher::new` / `EdgeCancelReconciler::new` / `with_filter*` variants without `_and_backend`). Runtime construction in `ff-engine/src/lib.rs` passes the backend through the new `with_filter_metrics_and_backend` constructors so the primary code path is trait-routed.

## Test plan

- [x] `cargo build --workspace` (clean)
- [x] `cargo clippy -p ff-core -p ff-backend-valkey -p ff-backend-postgres -p ff-backend-sqlite -p ff-engine --all-targets -- -D warnings` (clean)
- [x] `cargo test --workspace --lib` (all passing)
- [x] `cargo test --no-run --workspace` (all test targets compile)
- [x] `cargo build -p ff-backend-sqlite --no-default-features` (clean)
- [ ] CI gates (matrix tests + smoke-sqlite + feature-leak-guard + lua drift + publish-list drift + non_exhaustive + semver)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by avifenesh** [comment]
**Status: ready-for-review, blocked on #443 (Cluster 1 dependency).**

CI summary:
- 27 checks green (smoke-sqlite, feature-leak-guard, feature-propagation ff-backend-valkey/sqlite/core/engine/sdk/server/scheduler/observability/flowfabric, publish-list drift, non_exhaustive lint, lua drift, migration parity, cargo-machete, cargo-deny, unsafe ratchet, sqlite/postgres migration parity, all feature-propagation crates except ff-backend-postgres).
- **7 matrix-test failures all inherited from #443:** `scanner_namespace_filter_isolates_candidates` in ff-test fails on every Valkey target because cluster 1's new `should_skip_candidate(backend, ...)` routes through `describe_execution` which rejects the test's minimal exec_core seed. Details + options filed at #443.
- **feature-propagation (ff-backend-postgres)** also inherited from #443 (`cannot find module \`reconcilers\` in this scope` under the specific feature combo the guard uses).
- `cargo build --workspace`, `cargo clippy` on our crates, `cargo test --workspace --lib`, `cargo test --no-run --workspace`, `cargo build -p ff-backend-sqlite --no-default-features` all clean locally.

Cluster 3 diff is believed correct; once #443 merges, this PR will rebase onto main and CI should go green.
